name=input("Enter the Name")
age=input("Enter the age")
basic_salary=float(input("Enter the Basic Salary"))
total_salary=basic_salary+(basic_salary*5/100)+(basic_salary*10/100)
print("Total Salary with 5% DA and 10% HRA=",total_salary)